export const handValueRangeAxes = [
  {
    id: "progress_tenpai_axis",
    label: "進行度・聴牌率",
    shortLabel: "進行/聴牌",
    description:
      "シャンテン数、聴牌率、先制率、巡目に対する進行度を束ねる軸。旧『早さ』を実戦判断に接続しやすく再定義したもの。",
    tags: [
      "progress_tenpai_axis",
      "progress",
      "tenpai_rate",
      "shanten",
      "advance",
      "進行度",
      "聴牌率",
      "先制率",
    ],
    legacyAliases: ["speed_axis", "speed", "速度", "早さ"],
    metricTitles: [
      "進行度・聴牌率",
      "聴牌率",
      "先制率",
      "シャンテン進行度",
    ],
  },
  {
    id: "value_axis",
    label: "打点",
    shortLabel: "打点",
    description:
      "打点の高さやレンジを扱う軸。固定値ではなく、安い手から満貫級以上の尾部リスクまで幅を持って見る。",
    tags: [
      "value_axis",
      "value",
      "score_value",
      "打点",
      "打点レンジ",
      "満貫率",
      "高打点事故率",
    ],
    legacyAliases: [
      "value_distribution_axis",
      "value_distribution",
      "score_distribution",
      "打点分布",
      "打点レンジ推定",
    ],
    metricTitles: ["打点", "打点レンジ", "高打点事故率", "満貫以上率"],
  },
  {
    id: "wait_shape_quality_axis",
    label: "待ち・形の良さ",
    shortLabel: "待ち/形",
    description:
      "良形/愚形、待ち候補、変化のしやすさ、和了しやすさを扱う軸。危険牌比較や安全度評価にも接続する。",
    tags: [
      "wait_shape_quality_axis",
      "shape_axis",
      "wait_quality",
      "shape_quality",
      "wait_distribution",
      "danger_tile_comparison",
      "待ち",
      "形",
      "待ち・形",
      "待ち・形の良さ",
      "良形",
      "愚形",
      "安全度",
      "危険牌比較",
    ],
    legacyAliases: [
      "wait_danger_distribution_axis",
      "wait_distribution",
      "danger_tile_distribution",
      "shape",
      "危険牌分布",
      "待ち分布",
    ],
    metricTitles: [
      "待ち・形の良さ",
      "待ち候補",
      "形の良さ",
      "安全度",
      "危険牌比較",
    ],
  },
  {
    id: "score_situation_threshold_axis",
    label: "点数状況・行動閾値",
    shortLabel: "点数/閾値",
    description:
      "点棒状況、順位点、親子、局、巡目、供託、本場、条件戦によって、押し引きや危険牌選択の閾値がどう動くかを扱う軸。",
    tags: [
      "score_situation_threshold_axis",
      "score_situation",
      "action_threshold",
      "rank_ev",
      "rank_point",
      "score_context",
      "点数状況",
      "行動閾値",
      "順位期待値",
      "条件戦",
      "押し引き閾値",
    ],
    legacyAliases: [
      "situation_threshold_axis",
      "situation_value",
      "external_modifier",
      "局面価値",
      "局面条件",
      "点棒状況",
      "turn",
      "dealer",
      "honba",
      "riichi_sticks",
    ],
    metricTitles: [
      "点数状況・行動閾値",
      "点数状況",
      "押し引き閾値",
      "順位期待値",
      "条件戦価値",
    ],
  },
] as const;
