import {
  createCase,
  createKnowledgeEdge,
  createKnowledgeNode,
  createRule,
  createWorkspaceDocument,
} from "./factory";
import { workspaceDocumentSchema, type WorkspaceDocument } from "./schema";

const seededAt = "2026-05-05T00:00:00.000Z";

const node = (
  type: Parameters<typeof createKnowledgeNode>[0],
  overrides: Parameters<typeof createKnowledgeNode>[1],
) =>
  createKnowledgeNode(type, {
    created_at: seededAt,
    updated_at: seededAt,
    ...overrides,
  });

const edge = (overrides: Parameters<typeof createKnowledgeEdge>[0]) =>
  createKnowledgeEdge({
    created_at: seededAt,
    updated_at: seededAt,
    ...overrides,
  });

const rule = (overrides: Parameters<typeof createRule>[0]) =>
  createRule({
    created_at: seededAt,
    updated_at: seededAt,
    ...overrides,
  });

const commonSemantic = {
  probability_role: "none" as const,
  propagation_policy: "none" as const,
};

export const seedWorkspace: WorkspaceDocument = workspaceDocumentSchema.parse(
  createWorkspaceDocument({
    updated_at: seededAt,
    nodes: [
      node("concept", {
        id: "node_reading_mean_concentrated",
        title: "平均集中型の読み",
        summary: "候補が中心値周辺に寄る分布として扱う。",
        description:
          "打点、待ち、安全度が極端に割れないときに代表値と近傍を検討する。",
        tags: ["読みの分布", "打点レンジ推定", "安全度評価"],
        confidence: 0.7,
        applicability: ["中盤", "情報量が中程度"],
        stage: "仮説",
        actor: "他家",
        source_type: "theory",
        reproducibility: 0.65,
        pruning_hints: ["score_only"],
        distribution_family: "categorical",
        position: { x: 120, y: 80 },
        ...commonSemantic,
      }),
      node("concept", {
        id: "node_reading_interval_spread",
        title: "区間拡散型の読み",
        summary: "単一点ではなく幅を持つ候補集合として残す。",
        tags: ["読みの分布", "Top-k", "安全度評価"],
        confidence: 0.66,
        applicability: ["序盤", "中盤", "不確実性が高い"],
        stage: "仮説",
        actor: "他家",
        source_type: "theory",
        reproducibility: 0.62,
        pruning_hints: ["must_keep_top_k"],
        distribution_family: "interval",
        thresholds: [
          { name: "low", value: "0.15", note: "下限" },
          { name: "high", value: "0.55", note: "上限" },
        ],
        position: { x: 120, y: 220 },
        ...commonSemantic,
      }),
      node("concept", {
        id: "node_reading_bimodal",
        title: "二極化する読み",
        summary: "強い候補と弱い候補が同時に残る形。",
        tags: ["読みの分布", "相反仮説", "押し引き"],
        confidence: 0.62,
        applicability: ["中盤", "終盤", "対リーチ"],
        stage: "仮説",
        actor: "他家",
        source_type: "idea",
        reproducibility: 0.5,
        pruning_hints: ["must_keep_top_k"],
        distribution_family: "bimodal",
        formulas: ["push branch peak", "fold branch peak"],
        position: { x: 120, y: 360 },
        ...commonSemantic,
      }),
      node("concept", {
        id: "node_reading_multimodal",
        title: "多峰性の読み",
        summary: "複数の説明モデルが同時に立つ。",
        tags: ["読みの分布", "染め読み", "手役読み"],
        confidence: 0.58,
        applicability: ["中盤", "対副露"],
        stage: "仮説",
        actor: "他家",
        source_type: "theory",
        reproducibility: 0.48,
        pruning_hints: ["must_keep_top_k"],
        distribution_family: "multimodal",
        formulas: ["flush", "toitoi", "yakuhai back"],
        position: { x: 120, y: 500 },
        ...commonSemantic,
      }),
      node("concept", {
        id: "node_asymmetric_tail",
        title: "非対称テール",
        summary: "低確率でも損失が大きい側を厚く見る。",
        tags: ["読みの分布", "押し引き", "打点レンジ推定"],
        confidence: 0.64,
        applicability: ["終盤", "ラス目", "高打点気配"],
        stage: "判断",
        actor: "自分",
        source_type: "theory",
        reproducibility: 0.56,
        pruning_hints: ["hard_gate_candidate"],
        distribution_family: "asymmetric_tail",
        pruning_priority: 0.9,
        position: { x: 120, y: 640 },
        ...commonSemantic,
      }),
      node("signal", {
        id: "node_selection_bias",
        title: "選択バイアス",
        summary: "見えた事象だけで読みを固定する癖。",
        description:
          "semantic nodeとして保持し、確率は持たせない。ruleの注意書きから参照する。",
        tags: ["観測の癖", "レビュー", "安全度評価"],
        confidence: 0.74,
        applicability: ["全局面"],
        stage: "観測",
        actor: "自分",
        source_type: "note",
        reproducibility: 0.7,
        pruning_hints: ["score_only"],
        position: { x: 430, y: 80 },
        ...commonSemantic,
      }),
      node("signal", {
        id: "node_time_series_jump",
        title: "時系列ジャンプ",
        summary: "途中経過を飛ばして急に結論へ進む。",
        tags: ["観測の癖", "時系列", "レビュー"],
        confidence: 0.68,
        applicability: ["中盤", "終盤"],
        stage: "観測",
        actor: "自分",
        source_type: "note",
        reproducibility: 0.62,
        pruning_hints: ["score_only"],
        position: { x: 430, y: 220 },
        ...commonSemantic,
      }),
      node("condition", {
        id: "node_correlation_structure",
        title: "相関構造",
        summary: "複数シグナルの独立性を疑う。",
        tags: ["条件設計", "Soft score", "相手手牌推定"],
        confidence: 0.72,
        applicability: ["対副露", "中盤"],
        stage: "条件",
        actor: "全員",
        source_type: "theory",
        reproducibility: 0.66,
        pruning_hints: ["score_only"],
        position: { x: 430, y: 360 },
        ...commonSemantic,
      }),
      node("concept", {
        id: "node_player_type_mixture",
        title: "類型混合",
        summary: "プレイヤー類型を単一に決め打ちしない。",
        tags: ["観測の癖", "相手手牌推定", "Top-k"],
        confidence: 0.56,
        applicability: ["長期レビュー", "対特定類型"],
        stage: "仮説",
        actor: "特定類型",
        source_type: "idea",
        reproducibility: 0.42,
        pruning_hints: ["must_keep_top_k"],
        distribution_family: "mixture",
        position: { x: 430, y: 500 },
        ...commonSemantic,
      }),
      node("condition", {
        id: "node_state_abstraction",
        title: "State abstraction",
        summary: "局面情報を比較可能な状態へ圧縮する。",
        tags: ["条件設計", "pruning-ui", "Rule Builder"],
        confidence: 0.78,
        applicability: ["全局面"],
        stage: "条件",
        actor: "全員",
        source_type: "theory",
        reproducibility: 0.72,
        pruning_hints: ["can_prune"],
        position: { x: 740, y: 80 },
        ...commonSemantic,
      }),
      node("condition", {
        id: "node_hard_gate",
        title: "Hard gate",
        summary: "満たさない候補を明示的に除外する。",
        tags: ["条件設計", "Hard gate", "pruning-ui"],
        confidence: 0.8,
        applicability: ["条件分岐", "対リーチ"],
        stage: "条件",
        actor: "自分",
        source_type: "theory",
        reproducibility: 0.7,
        pruning_hints: ["hard_gate_candidate", "can_prune"],
        position: { x: 740, y: 220 },
        ...commonSemantic,
      }),
      node("metric", {
        id: "node_soft_score",
        title: "Soft score",
        summary: "弱い根拠を重みとして積む。",
        tags: ["条件設計", "Soft score", "pruning-ui"],
        confidence: 0.76,
        applicability: ["候補比較", "安全度評価"],
        stage: "条件",
        actor: "全員",
        source_type: "theory",
        reproducibility: 0.68,
        pruning_hints: ["score_only"],
        position: { x: 740, y: 360 },
        ...commonSemantic,
      }),
      node("exception", {
        id: "node_override",
        title: "Override",
        summary: "例外条件で一般則を上書きする。",
        tags: ["条件設計", "Override", "例外"],
        confidence: 0.75,
        applicability: ["終盤", "例外"],
        stage: "判断",
        actor: "自分",
        source_type: "theory",
        reproducibility: 0.62,
        pruning_hints: ["override_only"],
        position: { x: 740, y: 500 },
        ...commonSemantic,
      }),
      node("action", {
        id: "node_fallback",
        title: "Fallback",
        summary: "情報不足時の既定動作を決める。",
        tags: ["条件設計", "Fallback", "レビュー"],
        confidence: 0.68,
        applicability: ["情報不足", "ルール衝突"],
        stage: "判断",
        actor: "自分",
        source_type: "idea",
        reproducibility: 0.55,
        pruning_hints: ["can_prune"],
        position: { x: 740, y: 640 },
        ...commonSemantic,
      }),
      node("heuristic", {
        id: "node_top_k",
        title: "Top-k hypotheses",
        summary: "上位k個の仮説を意図的に残す。",
        tags: ["条件設計", "Top-k", "相反仮説"],
        confidence: 0.74,
        applicability: ["序盤", "中盤", "不確実性が高い"],
        stage: "仮説",
        actor: "自分",
        source_type: "theory",
        reproducibility: 0.66,
        pruning_hints: ["must_keep_top_k"],
        position: { x: 1040, y: 80 },
        ...commonSemantic,
      }),
      node("heuristic", {
        id: "node_hysteresis",
        title: "Hysteresis",
        summary: "小さな変化で判断が揺れすぎないようにする。",
        tags: ["条件設計", "Soft score", "押し引き"],
        confidence: 0.58,
        applicability: ["閾値付近", "終盤"],
        stage: "判断",
        actor: "自分",
        source_type: "idea",
        reproducibility: 0.48,
        pruning_hints: ["score_only"],
        position: { x: 1040, y: 220 },
        ...commonSemantic,
      }),
      node("condition", {
        id: "node_event_update",
        title: "Event-driven update",
        summary: "重要イベントで読みを更新する。",
        tags: ["条件設計", "時系列", "相手手牌推定"],
        confidence: 0.7,
        applicability: ["リーチ", "副露", "終盤"],
        stage: "条件",
        actor: "全員",
        source_type: "theory",
        reproducibility: 0.6,
        pruning_hints: ["can_prune"],
        position: { x: 1040, y: 360 },
        ...commonSemantic,
      }),
      node("scenario", {
        id: "node_theme_push_pull",
        title: "押し引き",
        summary: "和了価値と放銃損失の比較テーマ。",
        tags: ["対象テーマ", "押し引き", "安全度評価"],
        confidence: 0.72,
        applicability: ["対リーチ", "終盤", "点数状況"],
        stage: "判断",
        actor: "自分",
        source_type: "theory",
        reproducibility: 0.65,
        pruning_hints: ["hard_gate_candidate", "score_only"],
        position: { x: 1360, y: 80 },
        ...commonSemantic,
      }),
      node("scenario", {
        id: "node_theme_flush_read",
        title: "染め読み",
        summary: "色寄せ、副露、余剰牌から染め手を読む。",
        tags: ["対象テーマ", "染め読み", "対副露"],
        confidence: 0.64,
        applicability: ["対副露", "中盤"],
        stage: "仮説",
        actor: "他家",
        source_type: "replay",
        reproducibility: 0.5,
        pruning_hints: ["must_keep_top_k"],
        position: { x: 1360, y: 220 },
        ...commonSemantic,
      }),
      node("metric", {
        id: "node_theme_safety",
        title: "安全度評価",
        summary: "放銃率と放銃時損失を分けて見る。",
        tags: ["対象テーマ", "安全度評価", "押し引き"],
        confidence: 0.72,
        applicability: ["対リーチ", "終盤"],
        stage: "判断",
        actor: "自分",
        source_type: "theory",
        reproducibility: 0.68,
        pruning_hints: ["score_only"],
        position: { x: 1360, y: 360 },
        ...commonSemantic,
      }),
      node("heuristic", {
        id: "node_bad_shape_fixed",
        title: "愚形固定仮説",
        summary: "手順から愚形待ち固定を候補として残す。",
        tags: ["対象テーマ", "手役読み", "相手手牌推定"],
        confidence: 0.54,
        applicability: ["終盤", "リーチ後"],
        stage: "仮説",
        actor: "他家",
        source_type: "idea",
        reproducibility: 0.38,
        pruning_hints: ["must_keep_top_k"],
        position: { x: 1360, y: 500 },
        ...commonSemantic,
      }),
      node("metric", {
        id: "node_point_range",
        title: "打点レンジ推定",
        summary: "相手の打点を範囲として持つ。",
        tags: ["対象テーマ", "打点レンジ推定", "押し引き"],
        confidence: 0.62,
        applicability: ["対副露", "対リーチ", "終盤"],
        stage: "仮説",
        actor: "他家",
        source_type: "theory",
        reproducibility: 0.52,
        pruning_hints: ["score_only", "hard_gate_candidate"],
        position: { x: 1360, y: 640 },
        ...commonSemantic,
      }),

      node("choice_group", {
        id: "node_cg_flush",
        title: "Choice group: 染め読み3候補",
        summary: "染め本線 / 染め薄い / 染め否定を排他的候補として扱う。",
        tags: ["inference", "choice-group", "染め読み"],
        confidence: 0.8,
        probability_role: "control",
        propagation_policy: "normalize_siblings",
        distribution_family: "categorical",
        position: { x: 1700, y: 80 },
      }),
      node("hypothesis", {
        id: "node_flush_mainline",
        title: "染め本線",
        summary: "同色副露と余剰牌処理から染めが本線。",
        tags: ["inference", "染め読み"],
        confidence: 0.72,
        probability_role: "posterior",
        choice_group_id: "cg_flush_read",
        base_weight: 0.52,
        dynamic_weight: 0.08,
        prior_probability: 0.42,
        posterior_probability: 0.5,
        lock_mode: "none",
        distribution_family: "categorical",
        propagation_policy: "normalize_siblings",
        position: { x: 2000, y: 40 },
      }),
      node("hypothesis", {
        id: "node_flush_thin",
        title: "染め薄い",
        summary: "染め気配はあるが別役の説明も残る。",
        tags: ["inference", "染め読み", "Top-k"],
        confidence: 0.6,
        probability_role: "posterior",
        choice_group_id: "cg_flush_read",
        base_weight: 0.34,
        prior_probability: 0.38,
        posterior_probability: 0.33,
        lock_mode: "soft",
        lock_value: 0.12,
        distribution_family: "categorical",
        propagation_policy: "normalize_siblings",
        position: { x: 2000, y: 180 },
      }),
      node("hypothesis", {
        id: "node_flush_denied",
        title: "染め否定",
        summary: "序盤手順や切り順から染め以外を本線にする。",
        tags: ["inference", "染め読み"],
        confidence: 0.5,
        probability_role: "posterior",
        choice_group_id: "cg_flush_read",
        base_weight: 0.2,
        dynamic_weight: -0.04,
        prior_probability: 0.2,
        posterior_probability: 0.17,
        lock_mode: "none",
        distribution_family: "categorical",
        propagation_policy: "normalize_siblings",
        position: { x: 2000, y: 320 },
      }),
      node("choice_group", {
        id: "node_cg_wait_shape",
        title: "Choice group: 待ち形多峰性",
        summary:
          "愚形固定 / 両面固定 / トイツ処理をmultimodal候補として保持する。",
        tags: ["inference", "choice-group", "手役読み"],
        confidence: 0.68,
        probability_role: "control",
        propagation_policy: "normalize_siblings",
        distribution_family: "multimodal",
        position: { x: 1700, y: 520 },
      }),
      node("branch", {
        id: "node_bad_wait_branch",
        title: "愚形固定",
        summary: "手順から愚形待ち固定の枝を残す。",
        tags: ["inference", "multimodal", "手役読み"],
        confidence: 0.55,
        probability_role: "posterior",
        choice_group_id: "cg_wait_shape",
        base_weight: 0.42,
        prior_probability: 0.36,
        posterior_probability: 0.38,
        lock_mode: "keep_top_k",
        lock_value: 2,
        distribution_family: "multimodal",
        formulas: ["kanchan", "penchan"],
        propagation_policy: "normalize_siblings",
        position: { x: 2000, y: 480 },
      }),
      node("branch", {
        id: "node_ryanmen_branch",
        title: "両面固定",
        summary: "牌効率上の自然な両面固定。",
        tags: ["inference", "multimodal", "手役読み"],
        confidence: 0.58,
        probability_role: "posterior",
        choice_group_id: "cg_wait_shape",
        base_weight: 0.4,
        prior_probability: 0.42,
        posterior_probability: 0.4,
        lock_mode: "none",
        distribution_family: "multimodal",
        formulas: ["ryanmen"],
        propagation_policy: "normalize_siblings",
        position: { x: 2000, y: 620 },
      }),
      node("branch", {
        id: "node_toitsu_branch",
        title: "トイツ処理",
        summary: "対子処理から待ち候補が変化した枝。",
        tags: ["inference", "multimodal", "手役読み"],
        confidence: 0.45,
        probability_role: "posterior",
        choice_group_id: "cg_wait_shape",
        base_weight: 0.22,
        prior_probability: 0.22,
        posterior_probability: 0.22,
        lock_mode: "none",
        distribution_family: "multimodal",
        formulas: ["shanpon", "toitsu break"],
        propagation_policy: "normalize_siblings",
        position: { x: 2000, y: 760 },
      }),
      node("hypothesis", {
        id: "node_high_value_tail",
        title: "高打点事故率",
        summary: "薄いが重い高打点事故をasymmetric_tailとして保持する。",
        tags: ["inference", "押し引き", "asymmetric_tail"],
        confidence: 0.62,
        probability_role: "posterior",
        base_weight: 0.18,
        prior_probability: 0.14,
        posterior_probability: 0.14,
        lock_mode: "freeze_ratio",
        lock_value: 0.65,
        distribution_family: "asymmetric_tail",
        propagation_policy: "gated",
        pruning_priority: 0.95,
        position: { x: 2320, y: 80 },
      }),
      node("choice_group", {
        id: "node_cg_diffuse_branches",
        title: "Choice group: 薄く広い枝集合",
        summary: "各枝の質量差が小さく、平均近似の安全性を確認するseed。",
        tags: ["inference", "choice-group", "concentration", "training"],
        confidence: 0.62,
        probability_role: "control",
        propagation_policy: "normalize_siblings",
        distribution_family: "interval",
        position: { x: 2320, y: 220 },
      }),
      node("branch", {
        id: "node_diffuse_safe_1",
        title: "薄く広い枝A",
        summary: "低濃度で広く残る枝集合の一部。",
        tags: ["inference", "concentration", "diffuse"],
        confidence: 0.48,
        probability_role: "posterior",
        choice_group_id: "cg_diffuse_branches",
        concentration_group_id: "concentration_diffuse",
        base_weight: 0.25,
        prior_probability: 0.25,
        posterior_probability: 0.25,
        distribution_family: "interval",
        propagation_policy: "normalize_siblings",
        position: { x: 2600, y: 160 },
      }),
      node("branch", {
        id: "node_diffuse_safe_2",
        title: "薄く広い枝B",
        summary: "低濃度で広く残る枝集合の一部。",
        tags: ["inference", "concentration", "diffuse"],
        confidence: 0.5,
        probability_role: "posterior",
        choice_group_id: "cg_diffuse_branches",
        concentration_group_id: "concentration_diffuse",
        base_weight: 0.24,
        prior_probability: 0.24,
        posterior_probability: 0.24,
        distribution_family: "interval",
        propagation_policy: "normalize_siblings",
        position: { x: 2600, y: 280 },
      }),
      node("branch", {
        id: "node_diffuse_safe_3",
        title: "薄く広い枝C",
        summary: "低濃度で広く残る枝集合の一部。",
        tags: ["inference", "concentration", "diffuse"],
        confidence: 0.46,
        probability_role: "posterior",
        choice_group_id: "cg_diffuse_branches",
        concentration_group_id: "concentration_diffuse",
        base_weight: 0.26,
        prior_probability: 0.26,
        posterior_probability: 0.26,
        distribution_family: "interval",
        propagation_policy: "normalize_siblings",
        position: { x: 2600, y: 400 },
      }),
      node("branch", {
        id: "node_diffuse_safe_4",
        title: "薄く広い枝D",
        summary: "低濃度で広く残る枝集合の一部。",
        tags: ["inference", "concentration", "diffuse"],
        confidence: 0.44,
        probability_role: "posterior",
        choice_group_id: "cg_diffuse_branches",
        concentration_group_id: "concentration_diffuse",
        base_weight: 0.25,
        prior_probability: 0.25,
        posterior_probability: 0.25,
        distribution_family: "interval",
        propagation_policy: "normalize_siblings",
        position: { x: 2600, y: 520 },
      }),
      node("choice_group", {
        id: "node_cg_bimodal_push",
        title: "Choice group: 二極化枝集合",
        summary:
          "押す/引くの二峰が強く、細い第三枝だけを切っても影響が小さいseed。",
        tags: ["inference", "choice-group", "concentration", "bimodal"],
        confidence: 0.68,
        probability_role: "control",
        propagation_policy: "normalize_siblings",
        distribution_family: "bimodal",
        position: { x: 2920, y: 80 },
      }),
      node("branch", {
        id: "node_bimodal_push",
        title: "二極化: 押し本線",
        summary: "二極化枝集合の第一峰。",
        tags: ["inference", "concentration", "bimodal", "押し引き"],
        confidence: 0.64,
        probability_role: "posterior",
        choice_group_id: "cg_bimodal_push",
        concentration_group_id: "concentration_bimodal",
        base_weight: 0.47,
        prior_probability: 0.47,
        posterior_probability: 0.47,
        distribution_family: "bimodal",
        propagation_policy: "normalize_siblings",
        position: { x: 3200, y: 40 },
      }),
      node("branch", {
        id: "node_bimodal_fold",
        title: "二極化: 引き本線",
        summary: "二極化枝集合の第二峰。",
        tags: ["inference", "concentration", "bimodal", "押し引き"],
        confidence: 0.62,
        probability_role: "posterior",
        choice_group_id: "cg_bimodal_push",
        concentration_group_id: "concentration_bimodal",
        base_weight: 0.46,
        prior_probability: 0.46,
        posterior_probability: 0.46,
        distribution_family: "bimodal",
        propagation_policy: "normalize_siblings",
        position: { x: 3200, y: 180 },
      }),
      node("branch", {
        id: "node_bimodal_thin_tail",
        title: "二極化: 薄い第三枝",
        summary: "狭い濃度だけを削るutility評価用の枝。",
        tags: ["inference", "concentration", "bimodal", "utility"],
        confidence: 0.32,
        probability_role: "posterior",
        choice_group_id: "cg_bimodal_push",
        concentration_group_id: "concentration_bimodal",
        base_weight: 0.07,
        prior_probability: 0.07,
        posterior_probability: 0.07,
        distribution_family: "bimodal",
        propagation_policy: "normalize_siblings",
        position: { x: 3200, y: 320 },
      }),
      node("observation", {
        id: "node_obs_same_suit_meld",
        title: "同色副露観測",
        summary: "同色副露と色寄せ気配を観測した。",
        tags: ["inference", "observation", "染め読み"],
        confidence: 0.82,
        probability_role: "prior",
        base_weight: 0.25,
        dynamic_weight: 0.15,
        prior_probability: 0.25,
        posterior_probability: 0.25,
        distribution_family: "categorical",
        propagation_policy: "multiply_downstream",
        position: { x: 1700, y: 320 },
      }),
      node("weight_modifier", {
        id: "node_modifier_bias_caution",
        title: "選択バイアス注意",
        summary: "染め読みを過大評価しないためのweight modifier。",
        tags: ["inference", "weight-modifier", "レビュー"],
        confidence: 0.7,
        probability_role: "control",
        base_weight: -0.04,
        dynamic_weight: -0.06,
        distribution_family: "mixture",
        propagation_policy: "multiply_downstream",
        position: { x: 1700, y: 680 },
      }),
      node("metric", {
        id: "metric_fold_risk",
        title: "fold_risk 放銃率",
        summary: "放銃しやすさへの方向付き影響を集約するmetric。",
        tags: ["metric", "influence", "fold_risk"],
        confidence: 0.75,
        stage: "metric",
        actor: "全員",
        source_type: "theory",
        position: { x: 2580, y: 40 },
        ...commonSemantic,
      }),
      node("metric", {
        id: "metric_win_rate",
        title: "win_rate 和了率",
        summary: "和了できる確率方向のmetric。",
        tags: ["metric", "influence", "win_rate"],
        confidence: 0.72,
        stage: "metric",
        actor: "自分",
        source_type: "theory",
        position: { x: 2580, y: 160 },
        ...commonSemantic,
      }),
      node("metric", {
        id: "metric_speed",
        title: "speed 速度",
        summary: "手の進行速度と先制性のmetric。",
        tags: ["metric", "influence", "speed"],
        confidence: 0.7,
        stage: "metric",
        actor: "全員",
        source_type: "theory",
        position: { x: 2580, y: 280 },
        ...commonSemantic,
      }),
      node("metric", {
        id: "metric_value",
        title: "value 打点価値",
        summary: "和了時価値、打点、順位価値のmetric。",
        tags: ["metric", "influence", "value"],
        confidence: 0.73,
        stage: "metric",
        actor: "自分",
        source_type: "theory",
        position: { x: 2580, y: 400 },
        ...commonSemantic,
      }),
      node("metric", {
        id: "metric_safety",
        title: "safety 安全度",
        summary: "打牌候補の安全側評価metric。",
        tags: ["metric", "influence", "safety"],
        confidence: 0.76,
        stage: "metric",
        actor: "自分",
        source_type: "theory",
        position: { x: 2580, y: 520 },
        ...commonSemantic,
      }),
      node("metric", {
        id: "metric_rank_ev",
        title: "rank_ev 順位期待値",
        summary: "点数状況を含む順位価値metric。",
        tags: ["metric", "influence", "rank_ev"],
        confidence: 0.68,
        stage: "metric",
        actor: "自分",
        source_type: "theory",
        position: { x: 2580, y: 640 },
        ...commonSemantic,
      }),
      node("metric", {
        id: "metric_information_value",
        title: "information_value 情報価値",
        summary: "追加観測で曖昧性を減らせる価値のmetric。",
        tags: ["metric", "influence", "information_value"],
        confidence: 0.62,
        stage: "metric",
        actor: "自分",
        source_type: "idea",
        position: { x: 2580, y: 760 },
        ...commonSemantic,
      }),
      node("observation", {
        id: "node_midgame_unsuji_tedashi",
        title: "中盤の無筋手出し",
        summary: "中盤に無筋牌が手出しされた観測。",
        tags: ["influence", "観測", "対リーチ"],
        confidence: 0.74,
        stage: "観測",
        actor: "他家",
        source_type: "replay",
        position: { x: 2280, y: 260 },
        ...commonSemantic,
      }),
      node("observation", {
        id: "node_genbutsu_increase",
        title: "現物増加",
        summary: "安全に切れる現物候補が増えた観測。",
        tags: ["influence", "観測", "安全度評価"],
        confidence: 0.78,
        stage: "観測",
        actor: "自分",
        source_type: "replay",
        position: { x: 2280, y: 380 },
        ...commonSemantic,
      }),
      node("hypothesis", {
        id: "node_hand_value_rise",
        title: "手牌価値上昇",
        summary: "自手の打点や和了率が上がり、押し文脈が強くなる。",
        tags: ["influence", "押し引き", "value"],
        confidence: 0.7,
        probability_role: "posterior",
        base_weight: 0.48,
        posterior_probability: 0.48,
        distribution_family: "categorical",
        position: { x: 2280, y: 500 },
      }),
      node("ambiguity_marker", {
        id: "node_flush_safety_ambiguity",
        title: "染め色依存の安全度曖昧性",
        summary: "相手が染め本線でも、色次第で特定牌の安全度方向が割れる。",
        tags: ["influence", "ambiguity", "mixed"],
        confidence: 0.55,
        stage: "曖昧性",
        actor: "全員",
        source_type: "idea",
        position: { x: 2280, y: 620 },
        ...commonSemantic,
      }),
      node("observation_candidate", {
        id: "obs_candidate_tedashi_jihai_renda",
        title: "手出し字牌連打を確認",
        summary: "染め仮説と役牌バックの切り分けに使う追加観測。",
        tags: ["influence", "observation_candidate", "染め読み"],
        confidence: 0.66,
        resolves_targets: ["metric_safety", "metric_information_value"],
        expected_sign_gain: 0.42,
        expected_weight_gain: 0.28,
        expected_margin_gain: 0.18,
        pruning_safety_change: 0.24,
        observation_cost: 0.18,
        timeliness: 0.85,
        stage: "観測候補",
        actor: "自分",
        source_type: "idea",
        position: { x: 2280, y: 760 },
        ...commonSemantic,
      }),
      node("pruning_suggestion", {
        id: "node_prune_warning_flush_safety",
        title: "染め安全度は即prune禁止",
        summary:
          "mixed influenceが残るため、色依存の安全度枝を単一方向に潰さない。",
        tags: ["influence", "pruning", "warning"],
        confidence: 0.7,
        stage: "pruning",
        actor: "自分",
        source_type: "idea",
        position: { x: 2920, y: 620 },
        ...commonSemantic,
      }),
      node("weight_adjustment_suggestion", {
        id: "node_downweight_unknown_safety",
        title: "unknown safetyはdownweight",
        summary: "評価不能な安全度影響はpruneではなく重みを弱める。",
        tags: ["influence", "downweight", "unknown"],
        confidence: 0.64,
        stage: "pruning",
        actor: "自分",
        source_type: "idea",
        position: { x: 2920, y: 760 },
        ...commonSemantic,
      }),
      node("signal", {
        id: "node_narrow_point_prune_reading",
        title: "狭い一点だけ削る読み",
        summary: "薄い第三枝だけを削るが、全体分布はほぼ動かないutility seed。",
        tags: ["utility", "training", "concentration"],
        confidence: 0.45,
        applicability: ["レビュー", "押し引き"],
        stage: "評価",
        actor: "自分",
        source_type: "idea",
        position: { x: 2920, y: 900 },
        ...commonSemantic,
      }),
      node("signal", {
        id: "node_top2_mass_prune_reading",
        title: "上位2枝に強く効く読み",
        summary:
          "確率質量が大きい枝に効き、global impactが大きいutility seed。",
        tags: ["utility", "training", "concentration"],
        confidence: 0.72,
        applicability: ["レビュー", "押し引き"],
        stage: "評価",
        actor: "自分",
        source_type: "idea",
        position: { x: 2920, y: 1020 },
        ...commonSemantic,
      }),
      node("observation_candidate", {
        id: "obs_candidate_ambiguity_reducer",
        title: "ambiguityを大きく減らす観測",
        summary:
          "mixed signを一方向に寄せ、pruning safetyを上げるtraining seed。",
        tags: ["utility", "training", "observation_candidate"],
        confidence: 0.7,
        resolves_targets: ["metric_safety", "metric_information_value"],
        expected_sign_gain: 0.68,
        expected_weight_gain: 0.46,
        expected_margin_gain: 0.3,
        pruning_safety_change: 0.42,
        observation_cost: 0.22,
        timeliness: 0.82,
        stage: "観測候補",
        actor: "自分",
        source_type: "idea",
        position: { x: 2920, y: 1140 },
        ...commonSemantic,
      }),
      node("observation_candidate", {
        id: "obs_candidate_margin_stable",
        title: "signは動くがmarginは動かない観測",
        summary:
          "方向評価は更新するがprojection marginへの寄与が小さいtraining seed。",
        tags: ["utility", "training", "observation_candidate"],
        confidence: 0.54,
        resolves_targets: ["metric_information_value"],
        expected_sign_gain: 0.38,
        expected_weight_gain: 0.12,
        expected_margin_gain: 0.02,
        pruning_safety_change: 0.04,
        observation_cost: 0.25,
        timeliness: 0.55,
        stage: "観測候補",
        actor: "自分",
        source_type: "idea",
        position: { x: 2920, y: 1260 },
        ...commonSemantic,
      }),
    ],
    edges: [
      edge({
        id: "edge_interval_topk",
        source: "node_reading_interval_spread",
        target: "node_top_k",
        type: "supports",
        label: "幅を残す",
      }),
      edge({
        id: "edge_bimodal_topk",
        source: "node_reading_bimodal",
        target: "node_top_k",
        type: "supports",
        label: "相反仮説を保持",
      }),
      edge({
        id: "edge_bimodal_mean",
        source: "node_reading_bimodal",
        target: "node_reading_mean_concentrated",
        type: "contradicts",
        label: "平均だけでは潰せない",
      }),
      edge({
        id: "edge_selection_bias_rule",
        source: "node_selection_bias",
        target: "node_soft_score",
        type: "applies_to",
        label: "注意書き",
      }),
      edge({
        id: "edge_correlation_soft",
        source: "node_correlation_structure",
        target: "node_soft_score",
        type: "refines",
        label: "二重加点を抑える",
      }),
      edge({
        id: "edge_override_hard",
        source: "node_override",
        target: "node_hard_gate",
        type: "overrides",
        label: "例外が上書き",
      }),
      edge({
        id: "edge_flush_theme_to_cg",
        source: "node_theme_flush_read",
        target: "node_cg_flush",
        type: "exported_as",
        label: "inference layerへ投影",
        relation_layer: "semantic",
      }),
      edge({
        id: "edge_cg_flush_mainline",
        source: "node_cg_flush",
        target: "node_flush_mainline",
        type: "triggers",
        label: "choice member",
        relation_layer: "probabilistic",
        conditional_weight: 1,
        propagate_probability: false,
        edge_group_id: "cg_flush_read",
      }),
      edge({
        id: "edge_cg_flush_thin",
        source: "node_cg_flush",
        target: "node_flush_thin",
        type: "triggers",
        label: "choice member",
        relation_layer: "probabilistic",
        conditional_weight: 1,
        propagate_probability: false,
        edge_group_id: "cg_flush_read",
      }),
      edge({
        id: "edge_cg_flush_denied",
        source: "node_cg_flush",
        target: "node_flush_denied",
        type: "triggers",
        label: "choice member",
        relation_layer: "probabilistic",
        conditional_weight: 1,
        propagate_probability: false,
        edge_group_id: "cg_flush_read",
      }),
      edge({
        id: "edge_obs_to_flush_mainline",
        source: "node_obs_same_suit_meld",
        target: "node_flush_mainline",
        type: "supports",
        label: "observed weight",
        relation_layer: "probabilistic",
        conditional_weight: 0.8,
        propagate_probability: true,
        edge_group_id: "cg_flush_read",
      }),
      edge({
        id: "edge_obs_to_flush_denied",
        source: "node_obs_same_suit_meld",
        target: "node_flush_denied",
        type: "contradicts",
        label: "negative evidence",
        relation_layer: "probabilistic",
        conditional_weight: 0.4,
        propagate_probability: true,
        edge_group_id: "cg_flush_read",
      }),
      edge({
        id: "edge_bias_modifier_flush",
        source: "node_modifier_bias_caution",
        target: "node_flush_mainline",
        type: "refines",
        label: "overconfidence penalty",
        relation_layer: "probabilistic",
        conditional_weight: 1,
        propagate_probability: false,
      }),
      edge({
        id: "edge_flush_to_tail",
        source: "node_flush_mainline",
        target: "node_high_value_tail",
        type: "triggers",
        label: "打点事故率へ伝播",
        relation_layer: "probabilistic",
        conditional_weight: 0.7,
        transition_rule: "posterior * 0.7",
        propagate_probability: true,
      }),
      edge({
        id: "edge_cg_wait_bad",
        source: "node_cg_wait_shape",
        target: "node_bad_wait_branch",
        type: "triggers",
        label: "choice member",
        relation_layer: "probabilistic",
        conditional_weight: 1,
        edge_group_id: "cg_wait_shape",
      }),
      edge({
        id: "edge_cg_wait_ryanmen",
        source: "node_cg_wait_shape",
        target: "node_ryanmen_branch",
        type: "triggers",
        label: "choice member",
        relation_layer: "probabilistic",
        conditional_weight: 1,
        edge_group_id: "cg_wait_shape",
      }),
      edge({
        id: "edge_cg_wait_toitsu",
        source: "node_cg_wait_shape",
        target: "node_toitsu_branch",
        type: "triggers",
        label: "choice member",
        relation_layer: "probabilistic",
        conditional_weight: 1,
        edge_group_id: "cg_wait_shape",
      }),
      edge({
        id: "edge_cg_diffuse_1",
        source: "node_cg_diffuse_branches",
        target: "node_diffuse_safe_1",
        type: "triggers",
        label: "diffuse member",
        relation_layer: "probabilistic",
        conditional_weight: 1,
        edge_group_id: "cg_diffuse_branches",
      }),
      edge({
        id: "edge_cg_diffuse_2",
        source: "node_cg_diffuse_branches",
        target: "node_diffuse_safe_2",
        type: "triggers",
        label: "diffuse member",
        relation_layer: "probabilistic",
        conditional_weight: 1,
        edge_group_id: "cg_diffuse_branches",
      }),
      edge({
        id: "edge_cg_diffuse_3",
        source: "node_cg_diffuse_branches",
        target: "node_diffuse_safe_3",
        type: "triggers",
        label: "diffuse member",
        relation_layer: "probabilistic",
        conditional_weight: 1,
        edge_group_id: "cg_diffuse_branches",
      }),
      edge({
        id: "edge_cg_diffuse_4",
        source: "node_cg_diffuse_branches",
        target: "node_diffuse_safe_4",
        type: "triggers",
        label: "diffuse member",
        relation_layer: "probabilistic",
        conditional_weight: 1,
        edge_group_id: "cg_diffuse_branches",
      }),
      edge({
        id: "edge_cg_bimodal_push",
        source: "node_cg_bimodal_push",
        target: "node_bimodal_push",
        type: "triggers",
        label: "bimodal member",
        relation_layer: "probabilistic",
        conditional_weight: 1,
        edge_group_id: "cg_bimodal_push",
      }),
      edge({
        id: "edge_cg_bimodal_fold",
        source: "node_cg_bimodal_push",
        target: "node_bimodal_fold",
        type: "triggers",
        label: "bimodal member",
        relation_layer: "probabilistic",
        conditional_weight: 1,
        edge_group_id: "cg_bimodal_push",
      }),
      edge({
        id: "edge_cg_bimodal_tail",
        source: "node_cg_bimodal_push",
        target: "node_bimodal_thin_tail",
        type: "triggers",
        label: "bimodal member",
        relation_layer: "probabilistic",
        conditional_weight: 1,
        edge_group_id: "cg_bimodal_push",
      }),
      edge({
        id: "edge_narrow_reading_targets_tail",
        source: "node_narrow_point_prune_reading",
        target: "node_bimodal_thin_tail",
        type: "weakens",
        label: "狭い一点だけ削る",
        relation_layer: "probabilistic",
        conditional_weight: -0.2,
        propagate_probability: false,
        edge_group_id: "cg_bimodal_push",
      }),
      edge({
        id: "edge_top2_reading_targets_push",
        source: "node_top2_mass_prune_reading",
        target: "node_bimodal_push",
        type: "weakens",
        label: "上位質量へ効く",
        relation_layer: "probabilistic",
        conditional_weight: -0.35,
        propagate_probability: false,
        edge_group_id: "cg_bimodal_push",
      }),
      edge({
        id: "edge_top2_reading_targets_fold",
        source: "node_top2_mass_prune_reading",
        target: "node_bimodal_fold",
        type: "weakens",
        label: "上位質量へ効く",
        relation_layer: "probabilistic",
        conditional_weight: -0.35,
        propagate_probability: false,
        edge_group_id: "cg_bimodal_push",
      }),
      edge({
        id: "edge_unsuji_tedashi_fold_risk",
        source: "node_midgame_unsuji_tedashi",
        target: "metric_fold_risk",
        type: "influences",
        label: "fold_risk +",
        relation_layer: "influence",
        sign: "+",
        magnitude: 0.72,
        confidence: 0.76,
        context_gate: ["中盤", "手出し", "無筋"],
        combination_mode: "additive",
        evidence_refs: ["node_midgame_unsuji_tedashi"],
        note: "中盤の無筋手出しは放銃率方向に正で扱う。",
      }),
      edge({
        id: "edge_genbutsu_fold_risk",
        source: "node_genbutsu_increase",
        target: "metric_fold_risk",
        type: "influences",
        label: "fold_risk -",
        relation_layer: "influence",
        sign: "-",
        magnitude: 0.65,
        confidence: 0.82,
        context_gate: ["現物", "対リーチ"],
        combination_mode: "additive",
        evidence_refs: ["node_genbutsu_increase"],
      }),
      edge({
        id: "edge_genbutsu_safety",
        source: "node_genbutsu_increase",
        target: "metric_safety",
        type: "influences",
        label: "safety +",
        relation_layer: "influence",
        sign: "+",
        magnitude: 0.72,
        confidence: 0.84,
        context_gate: ["現物"],
        combination_mode: "additive",
      }),
      edge({
        id: "edge_hand_value_win_rate",
        source: "node_hand_value_rise",
        target: "metric_win_rate",
        type: "influences",
        label: "win_rate +",
        relation_layer: "influence",
        sign: "+",
        magnitude: 0.58,
        confidence: 0.7,
        context_gate: ["押し", "良形化"],
        combination_mode: "additive",
      }),
      edge({
        id: "edge_hand_value_value",
        source: "node_hand_value_rise",
        target: "metric_value",
        type: "influences",
        label: "value +",
        relation_layer: "influence",
        sign: "+",
        magnitude: 0.8,
        confidence: 0.78,
        context_gate: ["打点上昇"],
        combination_mode: "additive",
      }),
      edge({
        id: "edge_hand_value_fold_risk_push",
        source: "node_hand_value_rise",
        target: "metric_fold_risk",
        type: "influences",
        label: "push context fold_risk +",
        relation_layer: "influence",
        sign: "+",
        magnitude: 0.36,
        confidence: 0.62,
        context_gate: ["押し判断", "危険牌を押す"],
        combination_mode: "additive",
        ambiguity_group_id: "amb_push_value_risk",
        note: "手牌価値上昇そのものではなく、押し選択によりfold_riskが上がる。",
      }),
      edge({
        id: "edge_flush_mainline_safety_mixed",
        source: "node_flush_mainline",
        target: "metric_safety",
        type: "influences",
        label: "safety mixed by suit",
        relation_layer: "influence",
        sign: "mixed",
        magnitude: 0.64,
        confidence: 0.58,
        context_gate: ["染め色次第", "牌種依存"],
        combination_mode: "additive",
        ambiguity_group_id: "amb_flush_safety_by_suit",
        evidence_refs: ["node_flush_safety_ambiguity"],
        note: "染め本線は色次第で特定牌の安全度を上げも下げもする。",
      }),
      edge({
        id: "edge_flush_mainline_information_unknown",
        source: "node_flush_mainline",
        target: "metric_information_value",
        type: "influences",
        label: "information unknown",
        relation_layer: "influence",
        sign: "unknown",
        magnitude: 0.42,
        confidence: 0.35,
        context_gate: ["染め色未特定"],
        combination_mode: "additive",
        ambiguity_group_id: "amb_flush_information_unknown",
      }),
      edge({
        id: "edge_tedashi_jihai_disambiguates_flush",
        source: "obs_candidate_tedashi_jihai_renda",
        target: "node_flush_safety_ambiguity",
        type: "disambiguates",
        label: "染め仮説を切り分け",
        relation_layer: "influence",
        sign: "+",
        magnitude: 0.56,
        confidence: 0.68,
        context_gate: ["手出し字牌", "副露後"],
        combination_mode: "additive",
        ambiguity_group_id: "amb_flush_safety_by_suit",
      }),
      edge({
        id: "edge_flush_ambiguity_blocks_pruning",
        source: "node_flush_safety_ambiguity",
        target: "node_prune_warning_flush_safety",
        type: "blocks_pruning",
        label: "mixed blocks prune",
        relation_layer: "influence",
        sign: "-",
        magnitude: 0.7,
        confidence: 0.72,
        context_gate: ["mixed", "unresolved"],
        combination_mode: "override",
      }),
      edge({
        id: "edge_unknown_safety_downweight",
        source: "node_flush_mainline",
        target: "node_downweight_unknown_safety",
        type: "weakens",
        label: "unknown -> downweight",
        relation_layer: "influence",
        sign: "unknown",
        magnitude: 0.36,
        confidence: 0.58,
        context_gate: ["評価不能"],
        combination_mode: "additive",
      }),
    ],
    rules: [
      rule({
        id: "rule_push_pull_gate",
        name: "対リーチ押し引き Hard gate",
        category: "hard_gate",
        target_node_ids: [
          "node_theme_push_pull",
          "node_hard_gate",
          "node_asymmetric_tail",
          "node_high_value_tail",
        ],
        hard_gates: [
          "自分の和了価値が低く、無筋高打点候補が複数残る",
          "終盤で現物または準安全牌が十分にある",
        ],
        soft_score_terms: [
          {
            id: "term_hand_value",
            label: "自手の和了価値",
            weight: 0.7,
            note: "打点、テンパイ率、親番を分けて後で調整する。",
          },
          {
            id: "term_deal_in_loss",
            label: "放銃時損失",
            weight: -0.8,
            note: "高打点事故率のasymmetric_tailを別枠で確認する。",
          },
        ],
        override_conditions: ["ラス目で局収支より順位点価値が極端に高い"],
        fallback_behavior:
          "スコア差が小さい場合はTop-k仮説を残し、判断メモに保留理由を書く。",
        note: "MVP用の構造化例。",
      }),
      rule({
        id: "rule_flush_soft_score",
        name: "染め読み Soft score",
        category: "soft_score",
        target_node_ids: [
          "node_theme_flush_read",
          "node_soft_score",
          "node_correlation_structure",
          "node_flush_mainline",
          "node_flush_thin",
          "node_flush_denied",
        ],
        hard_gates: ["同色牌の副露または極端な同色切り偏りがある"],
        soft_score_terms: [
          {
            id: "term_suit_density",
            label: "同色保持密度",
            weight: 0.5,
            note: "捨て牌と副露を二重計上しない。選択バイアスにも注意。",
          },
          {
            id: "term_offsuit_cut",
            label: "余剰他色切り",
            weight: 0.35,
            note: "序盤の孤立牌処理とは区別する。",
          },
        ],
        override_conditions: ["役牌バックやトイトイなど、染め以外の説明が強い"],
        fallback_behavior: "多峰性として染め/非染めを並べる。",
        note: "semanticな選択バイアスnodeを注意書きとして参照する。",
      }),
      rule({
        id: "rule_topk_fallback",
        name: "Top-k保持 Fallback",
        category: "fallback",
        target_node_ids: [
          "node_top_k",
          "node_bad_wait_branch",
          "node_ryanmen_branch",
          "node_toitsu_branch",
        ],
        hard_gates: ["主要仮説の確信度差が0.15未満"],
        soft_score_terms: [
          {
            id: "term_evidence_count",
            label: "独立根拠数",
            weight: 0.4,
            note: "相関構造で独立性を確認する。",
          },
        ],
        override_conditions: ["明確な放銃回避ルールが発火している"],
        fallback_behavior: "上位2から3仮説を残して、判断列に採用理由を書く。",
        note: "完全自動推論ではなくレビュー可能な保持方針。",
      }),
    ],
    cases: [
      createCase({
        id: "case_seed_push_pull",
        title: "東3局 対リーチ押し引きレビュー",
        round: "東3局",
        honba: 1,
        riichi_sticks: 1,
        turn: 12,
        scores: { east: 31000, south: 24700, west: 18000, north: 26300 },
        dealer: "east",
        seat: "south",
        riichi_status: "親リーチあり",
        melds_summary: "自分0副露、他家は北家1副露",
        discard_notes:
          "親は6巡目にドラ周辺を手出し。11巡目の手出し後にリーチ。",
        observations: [
          "親リーチが12巡目",
          "自分は一向聴で打点3900程度",
          "現物が2枚ある",
          "危険牌候補にドラ跨ぎが残る",
        ],
        hypotheses: [
          "親の打点レンジが広い",
          "自手の和了価値が不足",
          "安全度評価を優先すべき",
        ],
        attached_node_ids: [
          "node_theme_push_pull",
          "node_asymmetric_tail",
          "node_hard_gate",
          "node_theme_safety",
          "node_top_k",
          "node_high_value_tail",
        ],
        selected_rule_ids: ["rule_push_pull_gate"],
        lane_assignments: {
          node_theme_safety: "observation",
          node_asymmetric_tail: "hypothesis",
          node_hard_gate: "condition",
          node_theme_push_pull: "decision",
          node_top_k: "hypothesis",
          node_high_value_tail: "hypothesis",
        },
        top_k_hypotheses: 3,
        decision_note:
          "押し返す候補と安全側候補を並べ、Hard gateと高打点事故率を確認する。",
        review_note: "放銃時損失の非対称テールを後から見直す。",
        created_at: seededAt,
        updated_at: seededAt,
      }),
      createCase({
        id: "case_seed_training_concentration",
        title: "Training: concentration と pruning utility",
        round: "南2局",
        honba: 0,
        riichi_sticks: 0,
        turn: 10,
        scores: { east: 28000, south: 25500, west: 23000, north: 23500 },
        dealer: "west",
        seat: "south",
        riichi_status: "なし",
        melds_summary: "対面が1副露、上家は門前",
        discard_notes: "二極化枝集合で押し/引きが拮抗。薄い第三枝だけが残る。",
        observations: [
          "確率質量は上位2枝に集中",
          "薄い第三枝を削ってもmarginはほぼ動かない",
          "追加観測でmixed signを解消できる",
        ],
        hypotheses: [
          "上位質量に効く読みはutilityが高い",
          "狭い一点だけ削る読みは過大評価しない",
        ],
        attached_node_ids: [
          "node_cg_bimodal_push",
          "node_bimodal_push",
          "node_bimodal_fold",
          "node_bimodal_thin_tail",
          "node_narrow_point_prune_reading",
          "node_top2_mass_prune_reading",
          "obs_candidate_ambiguity_reducer",
        ],
        selected_rule_ids: ["rule_topk_fallback"],
        lane_assignments: {
          node_cg_bimodal_push: "condition",
          node_bimodal_push: "hypothesis",
          node_bimodal_fold: "hypothesis",
          node_bimodal_thin_tail: "hypothesis",
          node_narrow_point_prune_reading: "observation",
          node_top2_mass_prune_reading: "decision",
          obs_candidate_ambiguity_reducer: "observation",
        },
        top_k_hypotheses: 2,
        decision_note:
          "上位2枝を残し、薄い第三枝のpruneではなく上位質量への影響を評価する。",
        review_note:
          "distribution shape, concentration, ambiguity, projection marginを説明するtraining case。",
        created_at: seededAt,
        updated_at: seededAt,
      }),
    ],
    saved_views: [
      {
        id: "view_push_pull",
        name: "押し引き研究",
        search: "",
        tag_filter: ["押し引き"],
        node_type_filter: [],
        created_at: seededAt,
      },
      {
        id: "view_inference",
        name: "Inference layer",
        search: "",
        tag_filter: ["inference"],
        node_type_filter: [],
        created_at: seededAt,
      },
      {
        id: "view_influence",
        name: "Influence layer",
        search: "",
        tag_filter: ["influence"],
        node_type_filter: [],
        created_at: seededAt,
      },
    ],
    pruning_actions: [
      {
        id: "action_seed_narrow_prune",
        action_type: "hard_prune",
        target_ids: ["node_bimodal_thin_tail"],
        strength: 1,
        rationale:
          "狭い第三枝だけを削った場合、global impactが小さいことを確認する。",
        created_at: seededAt,
      },
      {
        id: "action_seed_top2_downweight",
        action_type: "soft_downweight",
        target_ids: ["node_bimodal_push", "node_bimodal_fold"],
        strength: 0.32,
        rationale:
          "上位2枝に効く読みは小さなdownweightでもdistributionを動かす。",
        created_at: seededAt,
      },
      {
        id: "action_seed_freeze_diffuse",
        action_type: "freeze_concentration_band",
        target_ids: [
          "node_diffuse_safe_1",
          "node_diffuse_safe_2",
          "node_diffuse_safe_3",
          "node_diffuse_safe_4",
        ],
        strength: 0.8,
        rationale:
          "薄く広い枝集合は平均近似の候補として固定し、他の不確実部分に集中する。",
        created_at: seededAt,
      },
    ],
    impact_summaries: [
      {
        before_snapshot_id: "snapshot_seed_narrow_before",
        after_snapshot_id: "snapshot_seed_narrow_after",
        delta_mass: 0.035,
        changed_node_count: 3,
        dominant_branch_change: "stable: 二極化: 押し本線",
        ambiguity_change: 0,
        margin_change: 0.008,
        vector_delta_by_metric: {},
        notes:
          "薄い第三枝だけのhard pruneはselectiveだが、global impactは小さいseed例。",
      },
      {
        before_snapshot_id: "snapshot_seed_top2_before",
        after_snapshot_id: "snapshot_seed_top2_after",
        delta_mass: 0.24,
        changed_node_count: 3,
        dominant_branch_change: "二極化: 押し本線 -> 二極化: 引き本線",
        ambiguity_change: 0.12,
        margin_change: 0.19,
        vector_delta_by_metric: {
          metric_fold_risk: -0.08,
          metric_safety: 0.04,
        },
        notes:
          "上位質量に効くdownweightは、projection marginとdominant branchを動かすseed例。",
      },
    ],
    reading_utilities: [
      {
        target_id: "node_narrow_point_prune_reading",
        selective_pruning_ratio: 0.07,
        global_impact_score: 0.08,
        concentration_shift: 0.03,
        ambiguity_reduction: 0,
        resolution_gain: 0.02,
        projected_margin_gain: 0.01,
        cost_estimate: 0.25,
        utility_score: 0.07,
      },
      {
        target_id: "node_top2_mass_prune_reading",
        selective_pruning_ratio: 0.93,
        global_impact_score: 0.62,
        concentration_shift: 0.51,
        ambiguity_reduction: 0.08,
        resolution_gain: 0.16,
        projected_margin_gain: 0.24,
        cost_estimate: 0.35,
        utility_score: 0.58,
      },
      {
        target_id: "obs_candidate_ambiguity_reducer",
        selective_pruning_ratio: 0.42,
        global_impact_score: 0.38,
        concentration_shift: 0.2,
        ambiguity_reduction: 0.68,
        resolution_gain: 0.48,
        projected_margin_gain: 0.3,
        cost_estimate: 0.22,
        utility_score: 0.64,
      },
      {
        target_id: "obs_candidate_margin_stable",
        selective_pruning_ratio: 0.34,
        global_impact_score: 0.18,
        concentration_shift: 0.08,
        ambiguity_reduction: 0.32,
        resolution_gain: 0.16,
        projected_margin_gain: 0.02,
        cost_estimate: 0.25,
        utility_score: 0.23,
      },
    ],
    reading_chains: [
      {
        id: "chain_seed_observe_lock_prune_compare",
        case_id: "case_seed_training_concentration",
        summary: "observation -> hypothesis_split -> lock -> prune -> compare",
        steps: [
          {
            id: "step_observe_top2",
            step_type: "observation",
            source_ids: ["node_top2_mass_prune_reading"],
            target_ids: ["node_bimodal_push", "node_bimodal_fold"],
            before_snapshot_id: "",
            after_snapshot_id: "",
            rationale: "上位2枝に確率質量が集中していることを観測する。",
            note: "probability actionなし。concentration確認のみ。",
          },
          {
            id: "step_split_bimodal",
            step_type: "hypothesis_split",
            source_ids: ["node_cg_bimodal_push"],
            target_ids: [
              "node_bimodal_push",
              "node_bimodal_fold",
              "node_bimodal_thin_tail",
            ],
            before_snapshot_id: "",
            after_snapshot_id: "",
            rationale: "多段読みを二極化 + 薄い第三枝として分ける。",
            note: "branch structureを明示する。",
          },
          {
            id: "step_lock_diffuse",
            step_type: "lock",
            source_ids: ["node_cg_diffuse_branches"],
            target_ids: [
              "node_diffuse_safe_1",
              "node_diffuse_safe_2",
              "node_diffuse_safe_3",
              "node_diffuse_safe_4",
            ],
            before_snapshot_id: "",
            after_snapshot_id: "",
            rationale: "薄く広い枝集合を平均近似候補としてfreezeする。",
            note: "freeze ratio 0.85をMVP actionに変換する。",
          },
          {
            id: "step_prune_tail",
            step_type: "pruning",
            source_ids: ["node_narrow_point_prune_reading"],
            target_ids: ["node_bimodal_thin_tail"],
            before_snapshot_id: "",
            after_snapshot_id: "",
            rationale:
              "狭い第三枝だけをpruneし、delta_massが小さいことを見る。",
            note: "utility過大評価を避けるtraining step。",
          },
          {
            id: "step_compare",
            step_type: "compare",
            source_ids: ["action_seed_narrow_prune"],
            target_ids: ["node_bimodal_push", "node_bimodal_fold"],
            before_snapshot_id: "",
            after_snapshot_id: "",
            rationale: "before/afterでdominant branchとmarginを比較する。",
            note: "compare stepはdiff表示のみ。",
          },
        ],
        created_at: seededAt,
        updated_at: seededAt,
      },
      {
        id: "chain_seed_mixed_observe_safe_prune",
        case_id: "case_seed_training_concentration",
        summary:
          "mixed sign -> observation request -> sign resolution -> safe prune",
        steps: [
          {
            id: "step_mixed_sign",
            step_type: "direction_update",
            source_ids: ["node_flush_mainline"],
            target_ids: ["metric_safety"],
            before_snapshot_id: "",
            after_snapshot_id: "",
            rationale: "染め本線のsafety影響はmixedとして残す。",
            note: "mixedをunknownと混同しない。",
          },
          {
            id: "step_observe_request",
            step_type: "observation_request",
            source_ids: ["node_flush_safety_ambiguity"],
            target_ids: ["obs_candidate_ambiguity_reducer"],
            before_snapshot_id: "",
            after_snapshot_id: "",
            rationale: "何を見れば方向が寄るかをObservation Plannerから選ぶ。",
            note: "expected_sign_gain / cost ratioを見る。",
          },
          {
            id: "step_sign_resolution",
            step_type: "direction_update",
            source_ids: ["obs_candidate_ambiguity_reducer"],
            target_ids: ["metric_safety"],
            before_snapshot_id: "",
            after_snapshot_id: "",
            rationale: "追加観測でsign ambiguityを減らす。",
            note: "曖昧性が残る場合はprune禁止。",
          },
          {
            id: "step_safe_prune",
            step_type: "pruning",
            source_ids: ["obs_candidate_ambiguity_reducer"],
            target_ids: ["node_flush_denied"],
            before_snapshot_id: "",
            after_snapshot_id: "",
            rationale: "方向が固まった後だけ安全に枝を削る。",
            note: "top-k keep制約と矛盾しないことを確認する。",
          },
        ],
        created_at: seededAt,
        updated_at: seededAt,
      },
    ],
    averaging_safety: [
      {
        target_id: "cg_diffuse_branches",
        score: 0.78,
        label: "safe",
        reasons: [
          "variance proxyが小さい",
          "薄く広い枝集合でsingle peakがない",
          "小さなperturbationでdominant branchが動きにくい",
        ],
      },
      {
        target_id: "cg_flush_read",
        score: 0.45,
        label: "caution",
        reasons: [
          "top_k_massが高い",
          "染め色依存のmixed influenceが残る",
          "平均化前にObservation Plannerで確認する",
        ],
      },
      {
        target_id: "cg_bimodal_push",
        score: 0.24,
        label: "unsafe",
        reasons: [
          "二極化している",
          "上位2枝のmarginが小さい",
          "薄い第三枝だけを削っても結論は安定しない",
        ],
      },
    ],
    teaching_logs: [
      {
        case_id: "case_seed_training_concentration",
        action_id: "action_seed_narrow_prune",
        explanation_short: "狭い一点だけ削る読みはutilityが低いことがある。",
        explanation_full:
          "削った枝のselective_pruning_ratioが低く、delta_massとprojection marginがほぼ動かない。concentrationが上位2枝に寄っている場合、薄いtailだけのpruneは判断を変えにくい。",
        key_terms: [
          "concentration",
          "selective pruning",
          "delta_mass",
          "projection margin",
        ],
        created_at: seededAt,
      },
      {
        case_id: "case_seed_training_concentration",
        action_id: "action_seed_top2_downweight",
        explanation_short:
          "上位確率質量に効く読みはdistribution全体を動かしやすい。",
        explanation_full:
          "top_k_massが高い枝集合では、小さなdownweightでもdelta_massとdominant branchが変わる。utilityは削る枝数ではなく、どの確率質量に作用したかで評価する。",
        key_terms: [
          "top_k_mass",
          "global impact",
          "dominant branch",
          "reading utility",
        ],
        created_at: seededAt,
      },
    ],
    active_case_id: "case_seed_push_pull",
  }),
);
