from app.main import main, start_capture_thread
from app.mock_data import (
    AVAILABLE_MOCK_PATTERNS,
    DEFAULT_MOCK_PATTERN,
    LEGACY_MOCK_PATTERN,
    MOCK_DORA_INDICATOR_TILES,
    MOCK_DORA_INDICATOR_TILES_136,
    MOCK_DORA_INDICATOR_TILES_37,
    MOCK_HAND_TILES,
    MOCK_HAND_TILES_136,
    MOCK_HAND_TILES_37,
    MOCK_MELD_TILES,
    MOCK_MELD_TILES_136,
    MOCK_MELD_TILES_37,
    MOCK_DISCARD_EVENTS_136,
    build_mock_tracker,
    get_mock_inputs,
    tiles136_to_tiles37,
)
from app.tenhou_ui_bridge_client import TenhouUiBridgeClient
from app.tenhou_ui_bridge_mock_server import (
    DEFAULT_TENHOU_UI_BRIDGE_MOCK_HOST,
    DEFAULT_TENHOU_UI_BRIDGE_MOCK_PORT,
    TENHOU_UI_BRIDGE_MOCK_PAGE_NAME,
    build_mock_page_url,
    resolve_mock_web_root,
    run_mock_server,
)
from app.tenhou_ui_bridge_protocol import (
    DEFAULT_TENHOU_UI_BRIDGE_HOST,
    DEFAULT_TENHOU_UI_BRIDGE_PORT,
    DEFAULT_TENHOU_UI_BRIDGE_TIMEOUT_S,
    TENHOU_UI_BRIDGE_APP_TOGGLE_CONTROL_IDS,
    TENHOU_UI_BRIDGE_APP_TOGGLE_CONTROL_LABELS,
    TENHOU_UI_BRIDGE_CONTROL_IDS,
    TENHOU_UI_BRIDGE_CONTROL_LABELS,
    TenhouUiBridgeControl,
    TenhouUiBridgeToggleControl,
    TenhouUiBridgeStatus,
    VisibleHandState,
    build_tenhou_ui_bridge_ws_url,
    build_visible_hand_state,
    control_id_to_label,
    normalize_bridge_controls,
    normalize_bridge_toggle_controls,
    resolve_hand_index_by_tile37,
    resolve_hand_index_by_tile136,
    toggle_control_id_to_label,
)
from app.tenhou_ui_bridge_server import TenhouUiBridgeServer
from app.window import configure_window, exit_fullscreen, maximize_window, toggle_fullscreen
from capture.fragment_parser import (
    export_event_csv_text,
    export_event_rows,
    export_discards,
    export_round_summary,
    load_from_decrypted_lines,
    load_from_text,
    load_from_xml_text,
    parse_tag_fragment,
    resolve_seat_mapping,
    validate_game_state,
    validate_round_state,
)
from capture.pcap_replay import DEFAULT_TEST_PACKET_INTERVAL_MS, run_test_capture
from capture.state import normalize_tile136_id, tile136_to_tile37_spec, tile136_to_tile37_ui
from capture.xml_url_loader import extract_viewer_tw, load_from_xml_url, resolve_xml_log_url

# __all__ の一覧。
__all__ = [
    "AVAILABLE_MOCK_PATTERNS",
    "DEFAULT_TEST_PACKET_INTERVAL_MS",
    "DEFAULT_MOCK_PATTERN",
    "LEGACY_MOCK_PATTERN",
    "MOCK_DORA_INDICATOR_TILES",
    "MOCK_DORA_INDICATOR_TILES_136",
    "MOCK_DORA_INDICATOR_TILES_37",
    "MOCK_HAND_TILES",
    "MOCK_HAND_TILES_136",
    "MOCK_HAND_TILES_37",
    "MOCK_MELD_TILES",
    "MOCK_MELD_TILES_136",
    "MOCK_MELD_TILES_37",
    "MOCK_DISCARD_EVENTS_136",
    "DEFAULT_TENHOU_UI_BRIDGE_HOST",
    "DEFAULT_TENHOU_UI_BRIDGE_MOCK_HOST",
    "DEFAULT_TENHOU_UI_BRIDGE_MOCK_PORT",
    "DEFAULT_TENHOU_UI_BRIDGE_PORT",
    "DEFAULT_TENHOU_UI_BRIDGE_TIMEOUT_S",
    "build_mock_page_url",
    "build_mock_tracker",
    "build_tenhou_ui_bridge_ws_url",
    "build_visible_hand_state",
    "configure_window",
    "control_id_to_label",
    "export_event_csv_text",
    "export_event_rows",
    "export_discards",
    "export_round_summary",
    "exit_fullscreen",
    "get_mock_inputs",
    "load_from_decrypted_lines",
    "load_from_text",
    "load_from_xml_text",
    "load_from_xml_url",
    "main",
    "maximize_window",
    "normalize_tile136_id",
    "parse_tag_fragment",
    "extract_viewer_tw",
    "normalize_bridge_controls",
    "normalize_bridge_toggle_controls",
    "resolve_seat_mapping",
    "resolve_hand_index_by_tile37",
    "resolve_hand_index_by_tile136",
    "resolve_xml_log_url",
    "run_test_capture",
    "run_mock_server",
    "start_capture_thread",
    "TENHOU_UI_BRIDGE_APP_TOGGLE_CONTROL_IDS",
    "TENHOU_UI_BRIDGE_APP_TOGGLE_CONTROL_LABELS",
    "TENHOU_UI_BRIDGE_CONTROL_IDS",
    "TENHOU_UI_BRIDGE_CONTROL_LABELS",
    "TENHOU_UI_BRIDGE_MOCK_PAGE_NAME",
    "TenhouUiBridgeClient",
    "TenhouUiBridgeControl",
    "TenhouUiBridgeToggleControl",
    "TenhouUiBridgeServer",
    "TenhouUiBridgeStatus",
    "resolve_mock_web_root",
    "VisibleHandState",
    "toggle_control_id_to_label",
    "tile136_to_tile37_spec",
    "tile136_to_tile37_ui",
    "tiles136_to_tiles37",
    "toggle_fullscreen",
    "validate_game_state",
    "validate_round_state",
]


if __name__ == "__main__":
    main()
